"""
Django settings for carte project.

Generated by 'django-admin startproject' using Django 1.9.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# CLIENT_ID_GOOGLE = '952417233608-cm0tii0fos58qdkhrg4e912j4ol04d9m.apps.googleusercontent.com'
# CLIENT_SECRET_GOOGLE = 'JHOHxhDsksQ6bwlGzgUHWJq-'

# SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '952417233608-cm0tii0fos58qdkhrg4e912j4ol04d9m.apps.googleusercontent.com'
# SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'JHOHxhDsksQ6bwlGzgUHWJq-'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$ep*%(ffh29!z+^fge2sw317j(!)gx7d--la^eb@xtmj&mu!y)'

# SECURITY WARNING: don't run with debug turned on in production!sudo 
DEBUG = True
    # if DEBUG:
    # else:
    #     SECRET_KEY = os.environ['SECRET_KEY']

ALLOWED_HOSTS = []


if DEBUG:
    EMAIL_HOST = 'localhost'
    EMAIL_PORT = 1025
    EMAIL_HOST_USER = ''
    EMAIL_HOST_PASSWORD = ''
    EMAIL_USE_TLS = False
    DEFAULT_FROM_EMAIL = 'shashankagarwal181996@gmail.com'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'carte',
    # 'social.apps.django_app.default',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'carte.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'django.core.context_processors.csrf',
            ],
        },
    },
]

# AUTHENTICATION_BACKENDS = (
#    'social.backends.facebook.FacebookOAuth2',
#    'social.backends.google.GoogleOAuth2',
#    'social.backends.twitter.TwitterOAuth',
#    'django.contrib.auth.backends.ModelBackend',
# )



WSGI_APPLICATION = 'carte.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         # 'NAME': os.path.join(BASE_DIR, 'mysql'),
#         'NAME': 'carte_db',
#         'USER': 'myprojectuser',
#         'PASSWORD': 'password',
#         'HOST': 'localhost',
#         'PORT': '',

#         # 'NAME': get_env_variable('DATABASE_NAME'),
#         # 'USER': get_env_variable('DATABASE_USER'),
#         # 'PASSWORD': get_env_variable('DATABASE_PASSWORD'),
#         # 'HOST': '',
#         # 'PORT': '',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         # 'NAME': os.path.join(BASE_DIR, 'mysql'),
#         'NAME': 'dea2fprtjcu1ea',
#         'USER': 'bplhukgsenkrwj',
#         'PASSWORD': 'SJpOWTlV0S4h7s4gY6iFuoACxa',
#         'HOST': 'ec2-54-225-100-236.compute-1.amazonaws.com',
#         'PORT': '5432',

#         # 'NAME': get_env_variable('DATABASE_NAME'),
#         # 'USER': get_env_variable('DATABASE_USER'),
#         # 'PASSWORD': get_env_variable('DATABASE_PASSWORD'),
#         # 'HOST': '',
#         # 'PORT': '',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        # 'NAME': os.path.join(BASE_DIR, 'mysql'),
        'NAME': 'd3am2ero54f3pb',
        'USER': 'jaugpoxgvridnd',
        'PASSWORD': 'HyMGAdcUHmWa1lOXkdDGoCxa7u',
        'HOST': 'ec2-54-163-245-3.compute-1.amazonaws.com',
        'PORT': '5432',

        # 'NAME': get_env_variable('DATABASE_NAME'),
        # 'USER': get_env_variable('DATABASE_USER'),
        # 'PASSWORD': get_env_variable('DATABASE_PASSWORD'),
        # 'HOST': '',
        # 'PORT': '',
    }
}



# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR,'static'), 
)
MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(os.path.join(BASE_DIR), "static", "media")
#MEDIA_ROOT = '/Users/jmitch/Desktop/ecommerce/static/media/'

STATIC_ROOT = os.path.join(os.path.join(BASE_DIR), "static", "static_root")
