# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 21:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carte', '0007_auto_20161008_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.FloatField()),
                ('item_name', models.CharField(max_length=100)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rate_review',
            field=models.ManyToManyField(blank=True, to='carte.Rate_Review'),
        ),
    ]
